### ISSUE TITLE
Implement User Feed

### ISSUE THREAD

**Issue by blushi** [resonatecoop/user-api-old#5]
This social feed should return:
- Last added albums and tracks from followed artist user groups
- Last added public playlists from followed user groups
- Last recommended artists from followed user groups (if they set their recommended artists as public)

Various feed implementations should be discussed here first.
Should we build our one or look into third party services such as https://getstream.io/ for instance?

**Comment by webbienat** [comment]
Hello Marie,
I'm new with Github. I'm would like to give you feedback, but I don't get what is "user feed". Is is a personnalized view of the catalogue ?

**Comment by blushi** [comment]
@

> Hello Marie,
> I'm new with Github. I'm would like to give you feedback, but I don't get what is "user feed". Is is a personnalized view of the catalogue ?

It's a regular social media feed that displays update from artists/labels/curators (ie user groups) you follow (see description above for more details).
